export enum DroneModel {
  "dji_mavicmini" = "DJI_MAVICMINI",
  "dji_mavicair" = "DJI_MAVICAIR",
  "dji_mavicpro" = "DJI_MAVICPRO",
  "dji_mavic2" = "DJI_MAVIC2",
  "dji_mavic2zoom" = "DJI_MAVIC2ZOOM",
  "dji_mavic2pro" = "DJI_MAVIC2PRO",
  "dji_mavicair2" = "DJI_MAVICAIR2",
  "dji_mavicair2s" = "DJI_MAVICAIR2S",
  "dji_mavicair2zoom" = "DJI_MAVICAIR2ZOOM",
  "dji_mavicair2pro" = "DJI_MAVICAIR2PRO",
  "dji_mavicair2se" = "DJI_MAVICAIR2SE",
  "dji_mavic3" = "DJI_MAVIC3",
  "dji_mavic3cine" = "DJI_MAVIC3CINE",
  "dji_mavic3pro" = "DJI_MAVIC3PRO",
  "dji_mavic3zoom" = "DJI_MAVIC3ZOOM",
  "dji_phantom3" = "DJI_PHANTOM3",
  "dji_phantom4" = "DJI_PHANTOM4",
  "dji_phantom4pro" = "DJI_PHANTOM4PRO",
  "dji_phantom4advanced" = "DJI_PHANTOM4ADVANCED",
  "dji_phantom4rtk" = "DJI_PHANTOM4RTK",
  "dji_phantom4multispectral" = "DJI_PHANTOM4MULTISPECTRAL",
  "dji_phantom4prov2" = "DJI_PHANTOM4PROV2",
  "dji_phantom4rtkv2" = "DJI_PHANTOM4RTKV2",
  "dji_phantom4rtkv2datalinkpro" = "DJI_PHANTOM4RTKV2DATALINKPRO",
  "dji_phantom4rtkv2datalinkenterprise" = "DJI_PHANTOM4RTKV2DATALINKENTERPRISE",
  "dji_phantom4rtkv2datalinkrtk" = "DJI_PHANTOM4RTKV2DATALINKRTK",
}
